apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv

spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "default"
  hostPath:
    path: /data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudsync-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "default" 
  resources:
    requests:
      storage: 1Gi

# --------------------------------------------------      

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv1

spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "default"    
  hostPath:
    path: /data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudsync-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default" 
  resources:
    requests:
      storage: 1Gi

# --------------------------------------------------      

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv2

spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "default"    
  hostPath:
    path: /data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudsync-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default" 
  resources:
    requests:
      storage: 1Gi

# --------------------------------------------------      

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv3

spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "default"    
  hostPath:
    path: /data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudsync-pvc3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default" 
  resources:
    requests:
      storage: 1Gi

# --------------------------------------------------      

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv4

spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "default"    
  hostPath:
    path: /data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudsync-pvc4
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default" 
  resources:
    requests:
      storage: 1Gi

# --------------------------------------------------      