apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv-postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv-kafka
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/kafka

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv-elasticsearch
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/elasticsearch

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv-redis
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/redis
