apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv

spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudsync-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard" 
  resources:
    requests:
      storage: 1Gi