apiVersion: v1
kind: Service
metadata:
  name: cloudsync-tags-generation-service-Service
spec:
  selector:
    app: cloudsync-tags-generation-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
  sessionAffinity: ClientIP