apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  # This creates a "headless" service to provide a stable DNS
  # entry for the Zookeeper pod (e.g., zookeeper-0.zookeeper-svc)
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-svc
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      # -----------------------------------------------------------------
      # CORRECTED STRUCTURE: securityContext is a child of spec
      # -----------------------------------------------------------------
      securityContext:
        runAsUser: 1000
        fsGroup: 1000

      # -----------------------------------------------------------------
      # CORRECTED STRUCTURE: containers is a child of spec
      # -----------------------------------------------------------------
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.0.1
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper-0.zookeeper-svc.default.svc.cluster.local:2888:3888"
        volumeMounts:
        - name: cloudsync-pv
          mountPath: cloudsync-pvc
        - name: zookeeper-log
          mountPath: cloudsync-pvc
      
      # -----------------------------------------------------------------
      # CORRECTED STRUCTURE: volumes is a child of spec, not containers
      # -----------------------------------------------------------------
      volumes:
        - name: cloudsync-pv
          persistentVolumeClaim:
            claimName: cloudsync-pvc
        - name: zookeeper-log
          persistentVolumeClaim:
            claimName: cloudsync-pvc

  # Note: I'm using the default volumeClaimTemplates for StatefulSets
  # which is often cleaner, but the "volumes" block above will also work
  # if your PVCs (cloudsync-pv, zookeeper-log) already exist.
