apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  # Zookeeper must be running and resolvable at this address
  # for Kafka to start.
  server.properties: |
    log.dirs=/var/lib/kafka/data
    zookeeper.connect=zookeeper-svc.default.svc.cluster.local:2181
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    group.initial.rebalance.delay.ms=0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: broker
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: broker
  # This creates a "headless" service to provide a stable DNS
  # entry for the Kafka pod (e.g., kafka-0.kafka-headless)
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      # This fixes potential "Permission denied" errors on the volume
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.0.1
        ports:
        - containerPort: 9092
          name: broker
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-svc.default.svc.cluster.local:2181"
        # This points Kafka to the properties in the ConfigMap
        - name: KAFKA_PROPERTIES_FILE
          value: /etc/kafka/server.properties
        # This is the internal DNS name the broker will advertise
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://kafka-0.kafka-headless.default.svc.cluster.local:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        # Mounts for the data and config
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        - name: kafka-config
          mountPath: /etc/kafka
      volumes:
      - name: kafka-config
        configMap:
          name: kafka-config
      # --- UPDATED SECTION ---
      # This now points to your existing PVC
      - name: kafka-data
        persistentVolumeClaim:
          claimName: cloudsync-pvc
      # --- END OF UPDATE ---

