---
# =========================================================
# ZOOKEEPER SERVICE
# =========================================================

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service

spec:
  selector:
    app: zookeeper

  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

---
# =========================================================
# ZOOKEEPER STATEFULSET
# =========================================================

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper

spec:
  serviceName: zookeeper-service
  replicas: 1

  selector:
    matchLabels:
      app: zookeeper

  template:
    metadata:
      labels:
        app: zookeeper

    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.0.1

          ports:
            - containerPort: 2181

          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"

            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/lib/zookeeper/data

      volumes:
        - name: zookeeper-storage
          persistentVolumeClaim:
            claimName: cloudsync-pvc1

    ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudsync-pv-zookeeper

spec:
  capacity:
    storage: 5Gi

  volumeMode: Filesystem

  accessModes:
    - ReadWriteOnce

  storageClassName: standard

  hostPath:
    path: /data/zookeeper

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudsync-pvc1

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: standard

  volumeName: cloudsync-pv-zookeeper

  resources:
    requests:
      storage: 5Gi        
