apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-elasticsearch
  serviceName: "elasticsearch"  # Must match Service name
  template:
    metadata:
      labels:
        app: backend-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: xpack.security.enabled
              value: "false"  # Disable security for development
            - name: xpack.security.enrollment.enabled
              value: "false"
          volumeMounts:
            - name: cloudsync-pv3
              mountPath: /usr/share/elasticsearch/data  # Correct path
      volumes:
        - name: cloudsync-pv3
          persistentVolumeClaim:
            claimName: cloudsync-pvc3