---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  labels:
    app: metricbeat
data:
  metricbeat.yml: |
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false

    # Module: Monitor Elasticsearch
    metricbeat.modules:
    - module: elasticsearch
      xpack.enabled: true
      period: 10s
      hosts: ["http://elasticsearch:9200"] # Points to your existing Service

    # Output: Send to Elasticsearch
    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      # If you enabled security later, uncomment these:
      # username: "elastic"
      # password: "your_password"

    setup.kibana:
      host: "http://kibana:5601"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  labels:
    app: metricbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      containers:
        - name: metricbeat
          image: docker.elastic.co/beats/metricbeat:8.11.0 # Matches your ES version
          args: [
            "-c", "/etc/metricbeat.yml",
            "-e",
          ]
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: KIBANA_HOST
              value: kibana
          volumeMounts:
            - name: config
              mountPath: /etc/metricbeat.yml
              readOnly: true
              subPath: metricbeat.yml
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: metricbeat-config